#
# Requires [just](https://just.systems).

set unstable
set windows-shell := ["pwsh", "-C"]

CALL := if os_family() == "windows"  { "& " } else { "" }
HOST := "phoebe"

# Recipe that is executed when no recipe is given on the commandline.
[private]
list:
    @{{ CALL }}{{ quote(just_executable()) }} --justfile {{ quote(source_file()) }} --list --list-submodules

import "../../scripts/maintenance.just"

[group('deploy')]
[unix]
[working-directory("../..")]
[doc('Remotely update the phoebe configuration.')]
update *ARGS:
    nix run github:serokell/deploy-rs -- {{ quote(".#" + HOST) }} --remote-build {{ ARGS }}
