version = 1

[[annotations]]
path = ["hosts/**", "nix-darwin/**", "Justfile"]
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [".configurations/.vsconfig"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["*.lock"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["**/secrets.yaml", "**/secrets/*.yaml", "**/facter.json"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["**/topology.svg"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["nix/overlays/**/*.patch", "nixpkgs/**/*.patch"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["dotfiles/ssh/.ssh/keys.d/*.pub", "dotfiles/ssh/.ssh/*.pub"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"
