version = 1

[[annotations]]
path = [
    ".sops.yaml",
    "dotfiles/**",
    "home-manager/**",
    "hosts/**",
    "Justfile",
    "nix-darwin/**",
    "nixos/**",
    "nixpkgs/**",
]
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [".configurations/.vsconfig"]
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["*.lock"]
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"
