version = 1

[[annotations]]
path = [".configurations/.vsconfig"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["*.lock"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["**/secrets.yaml", "**/facter.json"]
precedence = "override"
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"
