version = 1


[[annotations]]
path = ["README.md", "hosts/README.md", "hosts/**/README.md"]
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = [
    ".configurations/**",
    ".dotter/**",
    ".editorconfig",
    ".envrc",
    ".gitattributes",
    ".github/**",
    ".gitignore",
    ".sops.yaml",
    "bin/**",
    "dotfiles/**",
    "flake.nix",
    "home-manager/**",
    "hosts/**",
    "Justfile",
    "nix-darwin/**",
    "nixos/**",
    "nixpkgs/**",
    "scripts/**",
    "treefmt.nix",
]
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = ["*.lock"]
SPDX-FileCopyrightText = "2025 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "0BSD"
