
"$schema" = 'https://starship.rs/config-schema.json'

palette = "catppuccin_macchiato"
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$guix_shell\
$nix_shell\
$direnv\
$env_var\
$custom\
$sudo\
$cmd_duration\
$line_break\
$time\
$status\
$os\
$container\
$shell\
$character"""

[custom.jj]
# TODO(PigeonF): Still quite slow on windows
# command = "jj --ignore-working-copy log -r@ -n1  --no-graph --color always -T starship"
description = "jj repository info"
detect_folders = [".jj"]
format = '[$symbol ($output )]($style)'
style = "bold purple"
symbol = "jj"

[character]
success_symbol = '[λ](bold green)'
error_symbol = '[✗](bold red)'

[cmd_duration]
min_time = 500

[directory]
use_os_path_sep = false

[direnv]
disabled = false

[hostname]
ssh_only = false

[shell]
format = "[$indicator]($style) "
nu_indicator = "nu "
unknown_indicator = "???"
disabled = false

[sudo]
disabled = false

[username]
show_always = true

# https://github.com/catppuccin/starship/

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
