# SPDX-FileCopyrightText: 2025 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD

[misc]
assume_yes = true
ignore_failures = ["system"]
cleanup = true

[windows]
self_rename = true
