[alacritty.files]

[bin.files]

[git.files]

[helix.files]

[jj.files]

[niri.files]
"dotfiles/niri/.config" = ""

[powershell.files]
"dotfiles/powershell" = ""

[pwsh.files]

[spicetify.files]

[ssh.files]

[starship.files]

[topgrade.files]

[vscodium.files]
"dotfiles/VSCodium/.config" = "~/Library/Application Support/"

[yazi.files]

[zellij.files]
