[alacritty.files]

[bin.files]

[git.files]

[helix.files]

[jj.files]

[niri.files]

[powershell.files]
"dotfiles/powershell" = ""

[pwsh.files]

[rio.files]

[spicetify.files]

[ssh.files]

[starship.files]

[topgrade.files]

[vscodium.files]

[yazi.files]

[zellij.files]
