# SPDX-FileCopyrightText: 2025 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD

[alacritty.files]

[bin.files]

[git.files]

[helix.files]

[jj.files]

[powershell.files]
"dotfiles/powershell" = ""

[pwsh.files]

[spicetify.files]

[ssh.files]

[starship.files]

[topgrade.files]

[zellij.files]
