# SPDX-FileCopyrightText: 2025 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD
#
# Requires [just](https://just.systems).

set unstable
set windows-shell := ["pwsh", "-C"]

CALL := if os_family() == "windows"  { "& " } else { "" }

[doc('MacBook used for macOS development')]
mod callisto
[doc('Desktop used as an SSH access station')]
mod europa
[doc('Laptop used for Linux development')]
mod ganymede
[doc('VM run on phoebe')]
mod oberon
[doc('VM run on phoebe')]
mod puck
[doc('Mac Mini used for development and hosting VMs')]
mod phoebe

# Recipe that is executed when no recipe is given on the commandline.
[private]
list:
    @{{ CALL }}{{ quote(just_executable()) }} --justfile {{ quote(source_file()) }} --list --list-submodules
