# SPDX-FileCopyrightText: 2025 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD
#
# Requires [just](https://just.systems).

set unstable

[doc('Laptop used for Linux development')]
mod ganymede

# Recipe that is executed when no recipe is given on the commandline.
[private]
list:
    @{{ quote(just_executable()) }} --justfile {{ quote(source_file()) }} --list --list-submodules
