# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2

# SPDX-FileCopyrightText: 2024 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD

properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      directives:
        description: Verify minimum OS version
        allowPrerelease: true
      settings:
        MinVersion: '10.0.26100'
  resources:
    - resource: Microsoft.Windows.Developer/DeveloperMode
      directives:
        description: Enable Developer Mode
        allowPrerelease: true
      settings:
        Ensure: Present
    - resource: xPSDesiredStateConfiguration/xRegistry
      directives:
        description: Enable long paths support
        allowPrerelease: true
      settings:
        Key: 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem'
        ValueName: LongPathsEnabled
        ValueData: 1
        ValueType: DWord
        Ensure: Present
    - resource: xPSDesiredStateConfiguration/xWindowsOptionalFeature
      directives:
        description: Enable Containres
        allowPrerelease: true
      settings:
        Name: Containers
        Ensure: Present
    - resource: xPSDesiredStateConfiguration/xWindowsOptionalFeature
      directives:
        description: Enable Hyper-V
        allowPrerelease: true
      settings:
        Name: Microsoft-Hyper-V-All
        Ensure: Present
    - resource: xPSDesiredStateConfiguration/xWindowsOptionalFeature
      directives:
        description: Enable Virtual Machine Platform
        allowPrerelease: true
      settings:
        Name: VirtualMachinePlatform
        Ensure: Present
    - resource: xPSDesiredStateConfiguration/xWindowsOptionalFeature
      directives:
        description: Enable Windows Hypervisor Platform
        allowPrerelease: true
      settings:
        Name: HypervisorPlatform
        Ensure: Present
    - resource: xPSDesiredStateConfiguration/xWindowsOptionalFeature
      directives:
        description: Enable Windows Sandbox
        allowPrerelease: true
      settings:
        Name: Containers-DisposableClientVM
        Ensure: Present
    - resource: xPSDesiredStateConfiguration/xWindowsOptionalFeature
      directives:
        description: Enable Windows Subsystem for Linux
        allowPrerelease: true
      settings:
        Name: Microsoft-Windows-Subsystem-Linux
        Ensure: Present
