
theme = "catppuccin_macchiato"

[editor]
cursorline = true
default-line-ending = "lf"
line-number = "relative"
rulers = [100, 120]
true-color = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[keys.normal]
"A-y" = ":yank-join"
