# [Alacritty Configuration](https://alacritty.org/config-alacritty.html).

[general]
import = [
    "themes/catppuccin-macchiato.toml",
    "terminal.toml",
    "keybindings.toml",
]

[env]
TERM = "alacritty"

[window]
padding = { x = 16, y = 9 }
dynamic_padding = true
resize_increments = true
option_as_alt = "OnlyLeft"

[scrolling]

[font]
normal = { family = "RecMonoDuotone Nerd Font", style = "Regular" }
bold = { family = "VictorMono Nerd Font", style = "Bold" }
italic = { family = "VictorMono Nerd Font", style = "Italic" }
bold_italic = { family = "VictorMono Nerd Font", style = "Bold Italic" }
size = 17
builtin_box_drawing = false

[bell]

[selection]

[cursor]
vi_mode_style = { shape = "Beam" }

[hints]

[debug]
