version = 1

[[annotations]]
# https://github.com/catppuccin/spicetify
path = ["catppuccin/**/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022-present Catppuccin Org <https://github.com/catppuccin>"
SPDX-License-Identifier = "MIT"
