# SPDX-FileCopyrightText: 2025 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD

includes = [".dotter/include/darwin.toml"]

packages = ["alacritty", "git", "helix", "jj", "ssh", "starship", "zellij"]
