# SPDX-FileCopyrightText: 2024 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD

includes = [".dotter/windows.toml"]

packages = [
  "alacritty",
  "bin",
  "git",
  "helix",
  "jj",
  "powershell",
  "pwsh",
  "spicetify",
  "starship",
  "topgrade",
]
