# SPDX-FileCopyrightText: 2025 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD

includes = [".dotter/include/windows.toml"]

packages = [
  "alacritty",
  "bin",
  "git",
  "helix",
  "jj",
  "powershell",
  "pwsh",
  "spicetify",
  "ssh",
  "topgrade",
  "vscodium",
]

# Documents folder is moved to S:, and is not in ~/
[files]
"dotfiles/pwsh/.config/powershell/Microsoft.PowerShell_profile.ps1.hbs" = "S:/Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"dotfiles/powershell/Microsoft.PowerShell_profile.ps1.hbs" = "S:/Documents/WindowsPowerShell/Microsoft.PowerShell_profile.ps1"
