[settings]
default_target_type = "symbolic"

[alacritty.files]
"dotfiles/alacritty/.config/" = "~/.config/"

[bin.files]
"bin/alarm.ps1" = ""

[git.files]
"dotfiles/git/.config/" = "~/.config/"
"dotfiles/git/.config/git/commit.gitconfig.hbs" = { target = "~/.config/git/commit.gitconfig", type = "template" }
"dotfiles/git/.config/git/windows.gitconfig.hbs" = { target = "~/.config/git/windows.gitconfig", type = "template" }

[helix.files]
"dotfiles/helix/.config/" = "~/.config/"

[jj.files]
"dotfiles/jj/.config/" = "~/.config/"

[niri.files]
"dotfiles/niri/.config" = "~/.config"

[powershell.files]
"dotfiles/powershell/" = ""

[pwsh.files]
"dotfiles/pwsh/.config" = "~/.config/"

[rio.files]
"dotfiles/rio/.config" = "~/.config/"

[spicetify.files]
"dotfiles/spicetify/.config/" = "~/.config/"

[ssh.files]
"dotfiles/ssh/.ssh" = { target = "~/.ssh", type = "template" }

[starship.files]
"dotfiles/starship/.config/" = "~/.config/"

[topgrade.files]
"dotfiles/topgrade/.config/" = "~/.config/"

[vscodium.files]
"dotfiles/VSCodium/.config" = "~/.config/"

[yazi.files]
"dotfiles/yazi/.config" = "~/.config/"
"dotfiles/yazi/.config/yazi/theme.toml.hbs" = { target = "~/.config/yazi/theme.toml", type = "template" }

[zellij.files]
"dotfiles/zellij/.config" = "~/.config/"
