# SPDX-FileCopyrightText: 2025 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: 0BSD

includes = [".dotter/include/nixos.toml"]

packages = ["git", "helix", "jj", "ssh", "starship", "yazi", "zellij"]
